### ISSUE TITLE
Features -> Options bug

### ISSUE THREAD

**Issue by kylebutts** [christian-hackyourshack/npm#3]
Hi, I'm super excited by this package! I'm on the website, and I think you have yet to actually move the features folder over to the options folder, so the links aren't working after [14e56fa](https://github.com/christian-hackyourshack/npm/commit/14e56fa2104c05d5e0018f853dd1559443f7418a)

**Comment by christian-hackyourshack** [comment]
Hi Kyle, thanks for the hint. I just fixed this. Enjoy. Happy Hacking, Christian
