### ISSUE TITLE
mdast not injected when using astro collections

### ISSUE THREAD

**Issue by eurghwhy** [christian-hackyourshack/npm#66]
Pretty self explanatory from the title: when using the new getCollection method provided by Astro to retrieve posts, the mdast tree is not injected into the frontmatter.

Astro Docs:
https://docs.astro.build/en/reference/api-reference/#getcollection.

**Comment by theor** [comment]
I think no feature works with getCollection - autoAbstract/title ain't doing anything either AFAIK.

**Comment by christian-hackyourshack** [comment]
Have you tried the remarkPluginFrontmatter property of the render result? As the docs for content collections state, remark is only executed when you call render(). m2dx is a remark plugin.

**Comment by christian-hackyourshack** [comment]
I am deprecating astro-m2dx for astro versions 2 and up in favor of individual packages/remark plugins. Hence, this will not be adressed for Astro 2.0 and later.
